name: fly
channels:
  - defaults
  - conda-forge
  - menpo
  - anaconda
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=7_kmp_llvm
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - anyio=4.10.0=py310h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py310hee96239_0
  - asttokens=3.0.0=py310h06a4308_0
  - async-lru=2.0.4=py310h06a4308_0
  - attr=2.5.2=h39aace5_0
  - attrs=24.3.0=py310h06a4308_0
  - aws-c-auth=0.9.0=h92a005d_16
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.5=h0c2b49e_1
  - aws-c-http=0.10.2=hee85082_3
  - aws-c-io=0.21.0=h1d8da38_1
  - aws-c-mqtt=0.13.1=h46c1de9_4
  - aws-c-s3=0.8.3=h9cdc349_1
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.32.10=h186f887_3
  - aws-sdk-cpp=1.11.510=h379b65b_14
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - babel=2.16.0=py310h06a4308_0
  - beautifulsoup4=4.13.5=py310h06a4308_0
  - binutils_impl_linux-64=2.39=he00db2b_1
  - binutils_linux-64=2.39=h5fc0e48_13
  - blas=1.0=openblas
  - bleach=6.2.0=py310h06a4308_0
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brian2=2.5.1=py310hc4a4660_2
  - brotlicffi=1.0.9.2=py310h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py310h4eded50_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py310h06a4308_0
  - cython=3.0.9=py310hc6cd4ac_0
  - debugpy=1.8.16=py310hbdd6827_0
  - decorator=5.2.1=py310h06a4308_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py310h06a4308_0
  - executing=2.2.1=py310h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - filelock=3.20.3=pyhd8ed1ab_0
  - gcc_impl_linux-64=10.4.0=h5231bdf_19
  - gcc_linux-64=10.4.0=h9215b83_13
  - gflags=2.2.2=h6a678d5_1
  - glew=2.2.0=h3abd4de_0
  - glfw3=3.2.1=0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - gsl=2.7.1=h917eeb2_1
  - gxx_impl_linux-64=10.4.0=h5231bdf_19
  - gxx_linux-64=10.4.0=h6e491c6_13
  - h11=0.16.0=py310h06a4308_0
  - httpcore=1.0.9=py310h06a4308_0
  - httpx=0.28.1=py310h06a4308_1
  - icu=75.1=he02047a_0
  - idna=3.7=py310h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-compute-runtime=24.35.30872.27=h84d6215_0
  - intel-gmmlib=22.9.0=hb700be7_0
  - ipykernel=6.30.1=py310h06a4308_0
  - ipython=8.30.0=py310h06a4308_0
  - ipython_pygments_lexers=1.1.1=py310h06a4308_0
  - ipywidgets=8.1.5=py310h06a4308_0
  - jax=0.6.2=pyhd8ed1ab_0
  - jaxlib=0.6.2=cpu_py310h772e2ea_1
  - jedi=0.19.2=py310h06a4308_0
  - jinja2=3.1.6=py310h06a4308_0
  - joblib=1.5.2=py310h06a4308_0
  - json5=0.9.25=py310h06a4308_0
  - jsonschema=4.25.0=py310h06a4308_0
  - jsonschema-specifications=2023.7.1=py310h06a4308_0
  - jupyter=1.1.1=py310h06a4308_0
  - jupyter-lsp=2.2.5=py310h06a4308_0
  - jupyter_client=8.6.3=py310h06a4308_0
  - jupyter_console=6.6.3=py310h06a4308_0
  - jupyter_core=5.8.1=py310h06a4308_0
  - jupyter_events=0.12.0=py310h06a4308_0
  - jupyter_server=2.16.0=py310h06a4308_0
  - jupyter_server_terminals=0.5.3=py310h06a4308_0
  - jupyterlab=4.4.7=py310h06a4308_0
  - jupyterlab_pygments=0.3.0=py310h06a4308_0
  - jupyterlab_server=2.27.3=py310h06a4308_0
  - jupyterlab_widgets=3.0.15=py310h06a4308_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libarrow=20.0.0=h019e7cd_8_cuda
  - libarrow-acero=20.0.0=hb826db4_8_cuda
  - libarrow-dataset=20.0.0=hb826db4_8_cuda
  - libarrow-flight=20.0.0=hc82974e_8_cuda
  - libarrow-flight-sql=20.0.0=h69308b4_8_cuda
  - libarrow-gandiva=20.0.0=h60a82a7_8_cuda
  - libarrow-substrait=20.0.0=h69308b4_8_cuda
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcap=2.77=h3ff7636_0
  - libcblas=3.9.0=5_h92ddd45_netlib
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.18.0=h4e3cde8_0
  - libdrm=2.4.125=hb03c661_1
  - libdrm-cos6-x86_64=2.4.65=4
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-devel_linux-64=10.4.0=hd38fd1e_19
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libgoogle-cloud=2.36.0=hc4361e1_1
  - libgoogle-cloud-storage=2.36.0=h0121fbd_1
  - libgrpc=1.71.0=h8e591d7_1
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libllvm17=17.0.6=hc9c083f_1
  - libllvm18=18.1.8=default_hddf928d_9
  - libllvm20=20.1.8=hecd9e04_0
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=h46f56fc_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.21.0=hd1b1c89_0
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_0
  - libparquet=20.0.0=h3f30f2e_8_cuda
  - libpciaccess=0.18=hd590300_0
  - libprotobuf=5.29.3=h7460b1f_3
  - libre2-11=2025.06.26=hba17884_0
  - libsanitizer=10.4.0=h5246dfb_19
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-devel_linux-64=10.4.0=hd38fd1e_19
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=259.1=h6569c3e_0
  - libthrift=0.21.0=h0e7cc3e_0
  - libtorch=2.7.1=cpu_generic_hd123cff_2
  - libudev1=259.1=h6569c3e_0
  - libutf8proc=2.10.0=h202a827_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.51.0=hb03c661_1
  - libx11-common-cos6-x86_64=1.6.4=4
  - libx11-cos6-x86_64=1.6.4=4
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h04c0eec_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=21.1.8=h4922eb0_0
  - lz4-c=1.10.0=h5888daf_1
  - mako=1.3.10=pyhd8ed1ab_0
  - markupsafe=3.0.2=py310h5eee18b_0
  - matplotlib-inline=0.1.7=py310h06a4308_0
  - mesa-libgl-cos6-x86_64=11.0.7=4
  - mesalib=25.0.5=h57bcd07_2
  - mistune=3.1.2=py310h06a4308_0
  - ml_dtypes=0.5.4=np2py310h3d4ba91_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - nbclient=0.10.2=py310h06a4308_0
  - nbconvert=7.16.6=py310h06a4308_0
  - nbconvert-core=7.16.6=py310h06a4308_0
  - nbconvert-pandoc=7.16.6=py310h06a4308_0
  - nbformat=5.10.4=py310h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - networkx=3.4.2=pyh267e887_2
  - nlohmann_json=3.12.0=h54a6638_1
  - nomkl=1.0=h5ca1d4c_0
  - notebook=7.4.5=py310h06a4308_0
  - notebook-shim=0.2.4=py310h06a4308_0
  - numexpr=2.11.0=py310hccd6f0b_1
  - numpy=1.26.4=py310hb13e2d6_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openssl=3.6.1=h35e630c_1
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optree=0.18.0=py310h03d9f68_0
  - orc=2.1.2=h17f744e_0
  - overrides=7.4.0=py310h06a4308_0
  - packaging=25.0=py310h06a4308_1
  - pandas=2.3.3=py310h0158d43_1
  - pandoc=3.8=h06a4308_0
  - pandocfilters=1.5.1=py310h06a4308_0
  - parso=0.8.4=py310h06a4308_0
  - pexpect=4.9.0=py310h06a4308_0
  - pip=25.2=pyhc872135_1
  - platformdirs=4.3.7=py310h06a4308_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prometheus_client=0.21.1=py310h06a4308_0
  - prompt-toolkit=3.0.52=py310h06a4308_0
  - prompt_toolkit=3.0.52=hd3eb1b0_0
  - psutil=7.0.0=py310hee96239_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.3=py310h06a4308_0
  - pyarrow=20.0.0=py310hff52083_2
  - pyarrow-core=20.0.0=py310h33d1a0a_2_cuda
  - pybind11=3.0.1=pyh97977ab_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.23=py310h06a4308_0
  - pygments=2.19.1=py310h06a4308_0
  - pyopencl=2025.2.6=py310hc563356_1
  - pyparsing=3.2.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-fastjsonschema=2.20.0=py310h06a4308_0
  - python-json-logger=3.2.1=py310h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytools=2025.2.5=pyhd8ed1ab_0
  - pytorch=2.7.1=cpu_generic_py310_h4c75a92_2
  - pytz=2025.2=py310h06a4308_0
  - pyyaml=6.0.2=py310h5eee18b_0
  - pyzmq=27.1.0=py310hcf8288c_0
  - qtconsole=5.7.0=py310h06a4308_0
  - qtpy=2.4.3=py310h06a4308_0
  - rdma-core=61.0=h192683f_0
  - re2=2025.06.26=h9925aae_0
  - readline=8.3=hc2a1206_0
  - referencing=0.30.2=py310h06a4308_0
  - requests=2.32.5=py310h06a4308_0
  - rfc3339-validator=0.1.4=py310h06a4308_0
  - rfc3986-validator=0.1.1=py310h06a4308_0
  - rpds-py=0.22.3=py310h4aa5aa6_0
  - s2n=1.5.22=h96f233e_0
  - send2trash=1.8.2=py310h06a4308_1
  - setuptools=80.9.0=py310h06a4308_0
  - siphash24=1.8=py310h7c4b9e2_1
  - six=1.17.0=py310h06a4308_0
  - sleef=3.9.0=ha0421bc_0
  - snappy=1.2.2=h03e3b7b_1
  - sniffio=1.3.0=py310h06a4308_0
  - soupsieve=2.5=py310h06a4308_0
  - spirv-tools=2025.4=hb700be7_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=py310h06a4308_0
  - sympy=1.14.0=py310h06a4308_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - terminado=0.18.1=py310h06a4308_0
  - tinycss2=1.4.0=py310h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.2.1=py310h06a4308_0
  - tornado=6.5.1=py310h5eee18b_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing-extensions=4.15.0=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - ucx=1.17.0=h53fb5aa_4
  - urllib3=2.5.0=py310h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.13=py310h06a4308_0
  - webencodings=0.5.1=py310h06a4308_1
  - websocket-client=1.8.0=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - widgetsnbextension=4.0.13=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.3.1
      - arrow==1.4.0
      - av==16.0.1
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dm-control==1.0.27
      - dm-env==1.6
      - dm-tree==0.1.8
      - etils==1.13.0
      - farama-notifications==0.0.4
      - flameprof==0.4
      - flygym==1.2.1
      - fonttools==4.60.1
      - fqdn==1.5.1
      - fsspec==2025.9.0
      - glfw==2.10.0
      - gymnasium==1.2.1
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - isoduration==20.11.0
      - jsonpointer==3.0.0
      - kiwisolver==1.4.9
      - labmaze==1.0.6
      - lark==1.3.0
      - llvmlite==0.43.0
      - lxml==6.0.2
      - matplotlib==3.10.7
      - mediapy==1.2.4
      - mujoco==3.2.7
      - numba==0.60.0
      - opencv-python==4.12.0.88
      - openvino==2025.4.0
      - openvino-telemetry==2025.2.0
      - pillow==12.0.0
      - protobuf==6.33.0
      - pygame-ce==2.5.6
      - pyopengl==3.1.10
      - rfc3987-syntax==1.1.0
      - scipy==1.11.4
      - tqdm==4.67.1
      - uri-template==1.3.0
      - webcolors==24.11.1
